export  const alumniData = [
    { id: 1, name: "TRISHNA KAUR", company: "ITC Ltd.", class: "2007" },
    { id: 2, name: "Sudeep Kumar Pattnaik", company: "Bajaj Markets", class: "2007" },
    { id: 3, name: "SHIVAM SHUKLA", company: "PAYU", class: "2009" },
    { id: 4, name: "Shikha Anand", company: "Counselor", class: "2006" },
    { id: 5, name: "SAURABH DWIVEDI", company: "GMR", class: "2006" },
    { id: 6, name: "Sanjay Mathur", company: "Prometeon Tyre Group", class: "1984" },
    { id: 7, name: "Sandeep Katta", company: "Allen Career", class: "2007" },
    { id: 8, name: "SAHIBA CHADHA", company: "KPMG", class: "2013" },
    { id: 9, name: "ROHINA BINTE ASHAN", company: "Consultant at UAE", class: "2015" },
    { id: 10, name: "Rajiv Kumar", company: "CII", class: "2007" },
    { id: 11, name: "Puja Singh", company: "Skill Aquistion International", class: "2007" },
    { id: 12, name: "Pranav Srivastava", company: "Grofi", class: "2005" },
    { id: 13, name: "PRABHJOT KHERA", company: "Mirchi", class: "2007" },
    { id: 14, name: "PANKAJ KUMAR", company: "Global Capital Market Ltd", class: "2006" },
    { id: 15, name: "NITIN Sethi", company: "Bridgestone Emai", class: "2007" },
    { id: 16, name: "NEHA BHAT", company: "Sunpharma", class: "2007" },
    { id: 17, name: "Navjit Singh Gill", company: "Trodat India", class: "2007" },
    { id: 18, name: "MRIGANKA CHAKLANOBISH", company: "Load Share Networks", class: "2008" },
    { id: 19, name: "MOHIT BHALLA", company: "GFK", class: "2010" },
    { id: 20, name: "KUSHAGR JAIN", company: "BDO Rise", class: "2015" },
    { id: 21, name: "Kishor Kunal", company: "Yes Bank", class: "2007" },
    { id: 22, name: "HITESH KAKKAR", company: "Gitam University", class: "2007" },
    { id: 23, name: "HIMANSHU BADLIA", company: "Shoppers Stop", class: "2014" },
    { id: 24, name: "HARSH MALIK", company: "Genpact", class: "2007" },
    { id: 25, name: "DHANANJAY VERMA", company: "AB InBev", class: "2016" },
    { id: 26, name: "DEEPTANSHU SHUKLA", company: "Blackrock", class: "2009" },
    { id: 27, name: "DAMANPREET Kaur Bomrah", company: "Akash Educational Services LTD.", class: "2014" },
    { id: 28, name: "CHANCHAL KUMAR JHA", company: "Aditya Birla Sun Life Mutual Fund", class: "2015" },
    { id: 29, name: "Biswajyoti Bhattacharya", company: "North East Small Finance Bank", class: "2005" },
    { id: 30, name: "AVIRAL BINDLE", company: "Supply Hotspot", class: "2008" },
    { id: 31, name: "Anurag Goyal", company: "BrewsNRoast", class: "2009" },
    { id: 32, name: "ANKUR KUMAR Singh", company: "UFLEX", class: "2012" },
    { id: 33, name: "Akshay Chawla", company: "Green Energy Innovation", class: "2005" },
    { id: 34, name: "AKSH RAGHAV", company: "Puma Group", class: "2015" },
    { id: 35, name: "AJAY PRATAP", company: "Tesco Bengaluru", class: "2007" },
    { id: 36, name: "AASTHA GAUR", company: "Investment Professional", class: "2007" },
  ]