export const visitingFacultyData = [
  { name: "Prof. Anurag Bhatia", expertise: "Digital Marketing" },
  { name: "Prof. Manoj Sharma", expertise: "Finance" },
  { name: "Dr. Raju Chotani", expertise: "Legal Aspects of Business" },
  { name: "Dr. Kapil Mohan", expertise: "Business Analytics" },
  {
    name: "Prof. Rishi Kapoor",
    expertise: "Sales and Distribution Management",
  },
  { name: "Dr. Sartaj Khera", expertise: "Marketing Management" },
  { name: "Prof. Soumitra Mookherjee", expertise: "International Business" },
  { name: "Prof. Madan Lal", expertise: "International Business" },
  { name: "Prof. Aviral Bindle", expertise: "International Business" },
  { name: "Prof. Sharad Mathur", expertise: "Marketing Management" },
  { name: "Prof. Vishesh Poswal", expertise: "Finance" },
  { name: "Prof. Suket Chauhan", expertise: "Business Analytics" },
  { name: "Prof. Dhruv Sood", expertise: "International Business" },
  { name: "Prof. Kapil Bali", expertise: "HRM and SCM" },
  { name: "Prof. Megha Sharma", expertise: "Environmental Studies" },
  { name: "Prof. Varun Jaggi", expertise: "Acing Corporate Skills" },
  { name: "Prof. Lovely Arya", expertise: "Business Communication" },
  { name: "Prof. Ruchika Duggal", expertise: "Corporate Grooming" },
  { name: "Prof. Prakrati Sinha", expertise: "HRM" },
  { name: "Dr. Shivani Agarwal", expertise: "HRM" },
];

export const guestSpeakerData = [
  {
    name: "Mr. Sutanu Chowdhury",
    expertise: "CHRO",
    company: "Spencer's Retail Ltd",
  },
  {
    name: "Mr. Rajiv Dubey",
    expertise: "Vice President Marketing",
    company: "Dabur India",
  },
  {
    name: "Mr. Pulock Bhattacharji",
    expertise: "Vice President",
    company: "BSE Institute Ltd.",
  },
  {
    name: "Mr. Satish Lakkaraju",
    expertise: "CEO",
    company: "NexGen Logistics (P) Ltd.",
  },
  {
    name: "Ms. Nidhi Chadha",
    expertise: "Vice President Capability",
    company: "RBS Natwest",
  },
  {
    name: "Mr. Priyankar Podder",
    expertise: "Vice President",
    company: "CitiBank",
  },
  {
    name: "Mr. Deepak Chawla",
    expertise: "Associate Vice President",
    company: "Times Television Network",
  },
  {
    name: "Mr. Sarfraz Hasan",
    expertise: "Director",
    company: "Business Development, The Ureka Education, UAE",
  },
  {
    name: "Mr. Goutam Datta",
    expertise: "Chief Informant & Digital Officer",
    company: "Bajaj Allianz Life Insurance Co. Ltd.",
  },
  {
    name: "Mr. Jenender Anand",
    expertise: "COO",
    company: "LML Electric Pvt. Ltd.",
  },
  { name: "Mr. Hitesh Sahni", expertise: "AVP", company: "JQR Sports" },
  { name: "Mr. Sanjeeb Lahiri", expertise: "CHRO", company: "GRP Ltd." },
  { name: "Mr. Jahangir Shaikh ", expertise: "HRBP", company: " Dhawan" },
  {
    name: "Mr. Rajat Banerji",
    expertise: "Chairman/Vice President - Corporate Affairs",
    company: "Indian Direct Selling Association (IDSA)",
  },
  {
    name: "Dr. Nidhi Saxena",
    expertise: "Business Head",
    company: "MG Motors",
  },
  { name: "Mr. Puneet Dua", expertise: "Director", company: "Ballebazi.com" },
  {
    name: "Mr. Dinesh Jain",
    expertise: "Founder & CEO",
    company: "Indian Maze Advisory",
  },
  {
    name: "Ms. Kanika",
    expertise: "Senior HR Business Partner & Talent Lead",
    company: "Zee Media Corporation Ltd.",
  },
  {
    name: "Mr. Sandeep Singh Sasan",
    expertise: "Deputy General Manager",
    company: "Shanghai Urban Corporation Group",
  },
  {
    name: "Mr. Nitin Sethi",
    expertise: "Assistant Treasurer",
    company: "Bridge Stone, Beligum",
  },
  {
    name: "Ms. Bhawana Dhawan",
    expertise: "Head HR",
    company: "Pladis Global",
  },
  {
    name: "Mr. Abhishek Dhaniwal",
    expertise: "Procurement Manager",
    company: "Basefarm AS",
  },
  { name: "Mr. Kapil Bali", expertise: "Head HR", company: "CM Logistics" },
  {
    name: "Mr. Nilanjan Mukherjee",
    expertise: "General Manager HR",
    company: "Relaxo Footwears Ltd.",
  },
  { name: "Mr. Mohit Bhalla", expertise: "Associate Director", company: "GFK" },
  {
    name: "Ms. Nikita Bose",
    expertise: "National Head",
    company: "Invoice Mart",
  },
  {
    name: "Mr. Amit Kavia",
    expertise: "Head HR",
    company: "Ecom Express Ltd.",
  },
  {
    name: "Mr. Tariq Mehmood",
    expertise: "Sr. Manager - Corporate HR",
    company: "DEN Network",
  },
  {
    name: "Mr. Jawed Ali",
    expertise: "Chief Internal Auditor",
    company: "Saudi Maintenance Company (Siyanco) Ltd. ,Riyadh",
  },
  { name: "Ms. Veena Kumari", expertise: "Manager", company: "SEBI" },
  {
    name: "Mr. Harbinder Singh Sokhi",
    expertise: "BSE IPF",
    company: "BSE Ltd.",
  },
  { name: "Mr. Manu Jain", expertise: "Co-Founder", company: "VAMA" },
  {
    name: "Ms. Garima Kaushik",
    expertise: "Senior Analyst",
    company: "Moody’s Analyst Knowledge Services",
  },
  {
    name: "Mr. Ajay Pratap Gaur",
    expertise: "Senior Manager - Transition",
    company: "Genpact",
  },
  {
    name: "Mr. Shashank Shekhar",
    expertise: "Training Manager",
    company: "PVR Cinemas",
  },
  {
    name: "Dr. Sanjay Jerath",
    expertise: "Dean",
    company: "Fravashi International Academy",
  },
  { name: "Mr. Adish Das", expertise: "Senior Manager", company: "Delhivery" },
  {
    name: "Mr. Rajiv Gatne",
    expertise: "Director",
    company: "Sunshine Healthcare Ltd.",
  },
  {
    name: "Mr. Vasant Awasthi",
    expertise: "Channel Business Manager",
    company: "Daikin Airconditioning India Ltd.",
  },
  {
    name: "Ms. Mona Sharma",
    expertise: "Manager - Procurement Operations",
    company: "Genpact",
  },
  {
    name: "Mr. Manas Garai",
    expertise: "Principal Engineer",
    company: "Nagarro",
  },
  { name: "Mr. Inbranjan", expertise: "Business Head", company: "Dailyhunt" },
  { name: "Mr. Gaurav Sawhney", expertise: "DGM", company: "Jumps Auto" },
  {
    name: "Ms. Ashwini Dasgupta",
    expertise: "Personal Development Corporate trainer",
    company: "Vedant Training & Consulting",
  },
  { name: "Mr. Amit Gupta", expertise: "Director", company: "Factoryal" },
  {
    name: "Mr. Mayank Kumar",
    expertise: "People Advisor",
    company: "Accenture",
  },
  {
    name: "Mr. Aravind Voruganti",
    expertise: "Vice President",
    company: "IDS Inc.",
  },
  {
    name: "Ms. Veena Kumar",
    expertise: "Director",
    company: "CEC-Competitive Edge Consultants",
  },
  {
    name: "Mr. Ankit Vij",
    expertise: "Managing Director",
    company: "Jaypee Brothers Medical Publishers",
  },
  {
    name: "Mr. Wael Azeem",
    expertise: "Manager India Operations",
    company: "The Ureka Education",
  },
  { name: "Mr. Tafheem Bashir Mir", expertise: "Educator", company: "" },
  {
    name: "Dr. Shubhra Chakraborty",
    expertise: "Founder & CEO",
    company: "Poshan",
  },
  { name: "Ms. Madhura Bagchi", expertise: "Manager", company: "Genpact" },
  {
    name: "Mr. Anurag Awasthi",
    expertise: "Advisory Consultant",
    company: "E&Y Global Services",
  },
  {
    name: "Mr. D.C. Singhal",
    expertise: "Ex.Tata Steel Executive",
    company: "Tata Steel",
  },
  {
    name: "Dr. Pratap Mohanty",
    expertise: "Associate Professor",
    company: "IIT Roorkee",
  },
  {
    name: "Ms. Manpryt Kaur",
    expertise: "Founder",
    company: "BroSis Services",
  },
  {
    name: "Mr. Amit Goon",
    expertise: "Independent Director",
    company: "Revenue Growth Leader",
  },
  { name: "Mr. Hemsingh Patle", expertise: "CoFounder", company: "GroKalp" },
  {
    name: "Mr. Prosenjit Mukherjee",
    expertise: "Group Head - HR",
    company: "SRKAY Consulting Group",
  },
  {
    name: "Mr. Himanshu Badlia",
    expertise: "Head of Marketing",
    company: "Shoppers Stop",
  },
  {
    name: "Mr. Sahil Khanna",
    expertise: "CEO & Youtuber",
    company: "Lapaas Digital Marketing & Intellectual Indies",
  },
  {
    name: "Ms. Maryline Laidin",
    expertise: "Co-Manager",
    company: "Campus France",
  },
  {
    name: "Ms. Shubhra Sharma",
    expertise: "Co-Manager",
    company: "Campus France",
  },
  {
    name: "Mr. Rachit Dhawan",
    expertise: "Co-Manager",
    company: "Campus France",
  },
  {
    name: "Mr. Saurabh Gupta",
    expertise: "General Manager HR",
    company: "RSPL Ltd.",
  },
  {
    name: "Ms. Tan Yet Mee",
    expertise: "Founder (International Speaker)",
    company: "ecoMinim",
  },
  {
    name: "Ms. Aarti Sharma",
    expertise: "Founder",
    company: "360 Degree Image Makeovers",
  },
  {
    name: "Mr. Mohan Khatri",
    expertise: "Project Manager",
    company: "Iris Software Inc.",
  },
  {
    name: "Mr. Ashish Kumar",
    expertise: "Service Delivery Manager I Mentor of Change - ATL",
    company: "TCS & ATL (NITI Aayog)",
  },
  {
    name: "Mr. Mayank Pandey",
    expertise: "Zonal HR Head (HRBP)",
    company: "Emami Limited",
  },
  { name: "Mr. Vivek Pradhan", expertise: "Senior Manager", company: "Nestle" },
  {
    name: "Mr. Avishkar Mehrotra",
    expertise: "Founder & Managing Partner",
    company: "Neo Navigate Pathways LLP",
  },
  { name: "Mr. M M H Beg", expertise: "Head HR", company: "Bharti Foundation" },
  {
    name: "Mr. Rajat Tikku",
    expertise: "Sales Manager",
    company: "Havells India Ltd.",
  },
  {
    name: "Mr. Warren Patrick",
    expertise: "Partners",
    company: "Ryan and Stan Partners LLP",
  },
  { name: "Mr. Atul Bhatnagar", expertise: "Director", company: "SunMoksha" },
  {
    name: "Mr. Rajeev Bhadauria",
    expertise: "Founder & Managing Partner",
    company: "Ebullient",
  },
  {
    name: "Mr. Rajesh Kamath",
    expertise: "Co-Founder & Director",
    company: "Chankya Consulting Chiranjeev Gurukul",
  },
  {
    name: "Mr. Tarun Singhal",
    expertise: "Director - Business Development",
    company: "Sopra Steria, India",
  },
  {
    name: "Mr. Atul Tripathi",
    expertise: "Ex-Big Data & AI Consultant",
    company: "National Security Council Secretariat",
  },
  {
    name: "Mr. Pankaj Aswani",
    expertise: "Vice President",
    company: "HDFC Bank Ltd.",
  },
  { name: "Mr. Viplov", expertise: "AGM HR", company: "HCL Technologies" },
  {
    name: "Mr. Aben Lal",
    expertise: "Executive Director",
    company: "Alliance Air(Retd.)",
  },
  { name: "Mr. Inbranjan", expertise: "Business Head", company: "Dailyhunt" },
];
