export const eventsData = {
  2024: [
    {
      id: "yoga-day",
      title: "International Yoga Day!",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `IMM's Vibrant Celebration of International Yoga Day!`,
      date: "June 21, 2024",
      photoCount: 10,
      href: "#",
    },
    {
      id: "ciao-2024",
      title: "CIAO 2024",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Saying CIAO to the unforgettable journey of Batch 2022-24!`,
      date: "May 4, 2024",
      photoCount: 15,
      href: "#",
    },
    {
      id: "holi-fiesta",
      title: "HOLI FIESTA @IMM CAMPUS",
      image: "http://v0.dev/placeholder.svg",
      gallery: [],
      description: `Vibrant splashes of joy! Staff and Students at IMM Business School come together to celebrate the festival of colors.`,
      date: "March 25, 2024",
      photoCount: 17,
      href: "#",
    },
  ],
  2023: [
    {
      id: "aagaman-july-13",
      title: "Aagaman July 13, 2023",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Aagaman July 13, 2023`,
      date: "July 13, 2023",
      photoCount: 6,
      href: "#",
    },
    {
      id: "aagaman-july-12",
      title: "Aagaman July 12, 2023",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Aagaman July 12, 2023`,
      date: "July 12, 2023",
      photoCount: 6,
      href: "#",
    },
    {
      id: "aagaman-july-11",
      title: "Aagaman July 11, 2023",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Aagaman July 11, 2023`,
      date: "July 11, 2023",
      photoCount: 6,
      href: "#",
    },
    {
      id: "aagaman-july-10",
      title: "Aagaman July 10, 2023",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Aagaman July 10, 2023`,
      date: "July 10, 2023",
      photoCount: 9,
      href: "#",
    },
    {
      id: "aagaman-july-08",
      title: "Aagaman July 08, 2023",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Aagaman July 08, 2023`,
      date: "July 08, 2023",
      photoCount: 6,
      href: "#",
    },
    {
      id: "aagaman-july-07",
      title: "Aagaman July 07, 2023",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Aagaman July 07, 2023`,
      date: "July 07, 2023",
      photoCount: 6,
      href: "#",
    },
    {
      id: "aagaman-july-06",
      title: "Aagaman July 06, 2023",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Aagaman July 06, 2023`,
      date: "July 06, 2023",
      photoCount: 7,
      href: "#",
    },
    {
      id: "aagaman-july-05",
      title: "Aagaman July 05, 2023",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Aagaman July 05, 2023`,
      date: "July 05, 2023",
      photoCount: 6,
      href: "#",
    },
    {
      id: "aagaman-july-04",
      title: "Aagaman July 04, 2023",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Aagaman July 04, 2023`,
      date: "July 04, 2023",
      photoCount: 6,
      href: "#",
    },
    {
      id: "aagaman-july-02",
      title: "Aagaman July 02, 2023",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Aagaman July 02, 2023`,
      date: "July 02, 2023",
      photoCount: 6,
      href: "#",
    },
    {
      id: "aagaman-july-01",
      title: "Aagaman July 01, 2023",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Aagaman July 01, 2023`,
      date: "July 01, 2023",
      photoCount: 6,
      href: "#",
    },
    {
      id: "international-certification-ceremony",
      title: "International Certification Ceremony",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `International Certification Ceremony\nIMM Business School, New Delhi, in association with the Gabelli Business School, Fordham, University`,
      date: "TBD",
      photoCount: 25,
      href: "#",
    },
    {
      id: "nsic-certificate-distribution",
      title: "NSIC Certificate Distribution",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `NSIC Certificate Distribution\nIMM Business School believes in the holistic development of students, focusing beyond an up-to-date`,
      date: "TBD",
      photoCount: 15,
      href: "#",
    },
    {
      id: "scribble-day",
      title: "Scribble Day",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Scribble Day\nIMM's Scribble Day held on May 17th, 2023 was a vibrant celebration for students gathered to scribbl`,
      date: "May 17, 2023",
      photoCount: 14,
      href: "#",
    },
    {
      id: "pratapgarh-farms-excursion",
      title: "Pratapgarh Farms Excursion",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Pratapgarh Farms Excursion\nIMM’s French club and Finance club, worked together to organise an incredible off-site bonding acti`,
      date: "TBD",
      photoCount: 11,
      href: "#",
    },
    {
      id: "public-elocution-competition-g20",
      title: "Public Elocution Competition on G20",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Public Elocution Competition on G20\nThe Soft skill club of IMM - Kaushal has organised a fantastic Public Speaking Elocution event on 21`,
      date: "TBD",
      photoCount: 7,
      href: "#",
    },
    {
      id: "meditation-workshop",
      title: "Meditation Workshop",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Meditation Workshop\nA group of Students and faculty of IMM Business School attended a Workshop on Meditation in collabo`,
      date: "TBD",
      photoCount: 5,
      href: "#",
    },
    {
      id: "udaipur-excursion",
      title: "Udaipur Excursion",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Udaipur Excursion\nIMM planned a student excursion program for its students of 2022-2024 PGDM batch to Udaipur, Rajasth`,
      date: "TBD",
      photoCount: 27,
      href: "#",
    },
    {
      id: "holi-celebration",
      title: "Holi Celebration",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Holi Celebration\nHoli is a reminder that despite our differences, we are all bound by love for one another. With thi`,
      date: "TBD",
      photoCount: 8,
      href: "#",
    },
    {
      id: "winter-bash",
      title: "Winter Bash",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Winter Bash\nCheers to the Winter Bash organized by the OPMAC Club. Our PGDM students and faculty members had a b`,
      date: "TBD",
      photoCount: 8,
      href: "#",
    },
    {
      id: "vasant-panchami",
      title: "Vasant Panchami",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Vasant Panchami\nThe Institute of Marketing and Management sought divine blessings from Goddess Saraswati on the occa`,
      date: "TBD",
      photoCount: 4,
      href: "#",
    },
    {
      id: "republic-day",
      title: "Republic Day",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Republic Day\nIMM Cultural Club - Parampara organised a republic day celebration for its students, faculty and sta`,
      date: "TBD",
      photoCount: 5,
      href: "#",
    },
    {
      id: "lohri-celebration",
      title: "Lohri Celebration",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Lohri Celebration\nStudents of Institute of Marketing and Management celebrated Lohri Festival on January 13,2023. Th`,
      date: "January 13, 2023",
      photoCount: 9,
      href: "#",
    },
  ],
  2022: [
    {
      id: "christmas-celebration",
      title: "Christmas Celebration",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Students of Institute of Marketing and Management celebrated at a Xmas Soiree on December 23, 2022.`,
      date: "December 23, 2022",
      photoCount: 11,
      href: "#",
    },
    {
      id: "thanksgiving-day",
      title: "International Thanksgiving Day",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `On the International Thanksgiving Day, 24th November, 2022, IMM organized a Blood Donation Camp.`,
      date: "November 24, 2022",
      photoCount: 8,
      href: "#",
    },
    {
      id: "manali-excursion",
      title: "Manali Excursion 2022",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `IMM organized an Educational Tour to Manali, for 5 days, starting from 16th Oct’22 to 21st Oct ’22.`,
      date: "October 16-21, 2022",
      photoCount: 28,
      href: "#",
    },
    {
      id: "international-convocation-dubai",
      title: "International Convocation Celebration @ Dubai",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `IMM organized its first International Convocation Ceremony @ Dubai, on 16th October, 2022.`,
      date: "October 16, 2022",
      photoCount: 13,
      href: "#",
    },
    {
      id: "halloween-face-painting",
      title: "Halloween Face Painting @IMM",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `It is as much fun to scare as to be scared! A group of PGDM students of the Cultural Club at IMM.`,
      date: "October 31, 2022",
      photoCount: 6,
      href: "#",
    },
    {
      id: "unity-marathon",
      title: "Unity Marathon",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Head straight, shoulder relaxed.. a few more miles and we won't collapse! With high spirits, the students participated.`,
      date: "TBD",
      photoCount: 4,
      href: "#",
    },
    {
      id: "diwali-celebration",
      title: "Diwali Celebration",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Diwali a Festival of Lights, a festival to celebrate togetherness with all the brightness around.`,
      date: "TBD",
      photoCount: 3,
      href: "#",
    },
    {
      id: "navratri-pooja",
      title: "Navratri Pooja",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `The Institute of Marketing & Management celebrated Navratri by organising Pooja on the occasion.`,
      date: "TBD",
      photoCount: 6,
      href: "#",
    },
    {
      id: "national-cinema-day",
      title: "National Cinema Day",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `IMM Cultural Club “PARAMPARA” organized a Movie Day out for its students and faculty members.`,
      date: "TBD",
      photoCount: 6,
      href: "#",
    },
    {
      id: "teachers-day-celebration",
      title: "Teachers Day Celebration",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Teachers Day was enthusiastically celebrated at the Institute of Marketing & Management Business School.`,
      date: "TBD",
      photoCount: 4,
      href: "#",
    },
    {
      id: "dilli-darshan",
      title: "DILLI Darshan – A Students’ Day Out",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `AAGAMAN -2022, IMM’s Induction Program included a Students’ Day Out to visit various eminent places.`,
      date: "TBD",
      photoCount: 9,
      href: "#",
    },
    {
      id: "business-model-activity",
      title: "Building a Business Model",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Dr. Preshni Shrivastava Associate Professor IMM, organized a Business Model activity on the theme.`,
      date: "TBD",
      photoCount: 8,
      href: "#",
    },
    {
      id: "imms-got-talent",
      title: "IMM’s got Talent",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `The Institute of Marketing & Management had AAGAMAN-2022, Induction and Orientation Week from 1st to 7th April.`,
      date: "April 1-7, 2022",
      photoCount: 11,
      href: "#",
    },
    {
      id: "aagaman-2022",
      title: "AAGAMAN 2022 @IMM Induction Program",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `IMM Business School organized a one week Induction Program, AAGAMAN 2022, for students of the new PG.`,
      date: "April 1-7, 2022",
      photoCount: 19,
      href: "#",
    },
    {
      id: "ganesh-chaturthi",
      title: "Ganesh Chaturthi",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `On the occasion of Ganesh Chaturthi, Students, Faculty and Staff members of Institute of Marketing and Management celebrated.`,
      date: "TBD",
      photoCount: 9,
      href: "#",
    },
    {
      id: "janamashtami",
      title: "Janamashtami",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `The Cultural Club @ IMM “Parampara” celebrated Krishna Janam “Janamashtami” on 18th August.`,
      date: "August 18, 2022",
      photoCount: 8,
      href: "#",
    },
    {
      id: "international-yoga-day",
      title: "International Yoga Day",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Yoga brings balance between body, soul and mind. It helps us to understand the purpose of life and health.`,
      date: "June 21, 2022",
      photoCount: 3,
      href: "#",
    },
    {
      id: "beat-the-heat",
      title: "Beat the Heat",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `IMM Cultural club “Parampara” organized a scribbling day for the students of 2020-2022 batch.`,
      date: "TBD",
      photoCount: 4,
      href: "#",
    },
    {
      id: "ciao-2022",
      title: "CIAO-2022",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `"CIAO means to see off or say goodbye to someone who is very special to us. IMM Cultural Team “Parampara”.`,
      date: "TBD",
      photoCount: 4,
      href: "#",
    },
    {
      id: "game-on",
      title: "GAME ON",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `"IMM Sports Club "IMM SQUAD" organized a two day Sports Carnival "GAME ON" on 7' & 8' April.`,
      date: "April 7-8, 2022",
      photoCount: 10,
      href: "#",
    },
    {
      id: "april-cool-day",
      title: "April Cool Day",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `IMM CULTURAL CLUB "PARAMPARA" organized April Cool Day on 1st April 2022, where students and teachers participated.`,
      date: "April 1, 2022",
      photoCount: 3,
      href: "#",
    },
    {
      id: "bolly-holi-2022",
      title: "Bolly Holi 2022",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `The Cultural Club @ IMM-Parampara celebrated the festival of colors; Holi with a Bollywood twist this year.`,
      date: "March 18, 2022",
      photoCount: 3,
      href: "#",
    },
    {
      id: "vasant-panchami",
      title: "Celebrating Vasant Panchami, Murtisthapana followed by Pooja",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Vasant Panchami was held in grandeur. The Institute of Marketing and Management was fully prepared to celebrate.`,
      date: "February 5, 2022",
      photoCount: 3,
      href: "#",
    },
    {
      id: "celebrating-india",
      title: "Celebrating India",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `While the country and especially the capital New Delhi, has been undergoing strict restrictions due to the pandemic.`,
      date: "TBD",
      photoCount: 1,
      href: "#",
    },
  ],
  2021: [
    {
      id: "holi-celebration",
      title: "Holi Celebration",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `IMM students celebrated Holi with all the Faculty and staff members online on 27th March 2020. Stud`,
      date: "March 27, 2020",
      photoCount: 2,
      href: "#",
    },
    {
      id: "paw-party",
      title: "Paw Party @IMM",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Stray Dogs Outreach Program at the Institute of Marketing & Management. IMM Students organized a muc`,
      date: "TBD",
      photoCount: 3,
      href: "#",
    },
    {
      id: "imm-xmas-soiree",
      title: "IMM Xmas Soiree 2021",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `IMM Christmas Celebrations were held at Vasant Vihar Club. “Tis the Season to be Jolly”. The hol`,
      date: "December 25, 2021",
      photoCount: 3,
      href: "#",
    },
    {
      id: "diwali-celebration",
      title: "Diwali Celebration 2021",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `The Festival of Lights-Diwali was celebrated with great joy by Team IMM. The celebration began with`,
      date: "November 4, 2021",
      photoCount: 5,
      href: "#",
    },
    {
      id: "masquerade-2021",
      title: "Masquerade 2021",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Students of IMM celebrated Halloween 2021 with great enthusiasm and excitement. The fun-filled spook`,
      date: "October 31, 2021",
      photoCount: 8,
      href: "#",
    },
    {
      id: "imm-manali-trip",
      title: "IMM 2021 Manali Trip",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Spanning over 5 whole days, the IMM Manali trip turned out to be a tour that will remain in the hear`,
      date: "October 16-21, 2021",
      photoCount: 7,
      href: "#",
    },
    {
      id: "navotsav",
      title: "Navotsav",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `IMM celebrated Navotsav 2021 on the occasion of the 6th day of Navratras. The 9 days of prayers and`,
      date: "October 13, 2021",
      photoCount: 7,
      href: "#",
    },
    {
      id: "pratapgarh-farms",
      title: "Pratapgarh Farms",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Commemorating the eve of the 152nd Birth Anniversary of Mahatma Gandhi, the Father of Our Nation, an`,
      date: "October 2, 2021",
      photoCount: 8,
      href: "#",
    },
    {
      id: "money-heist-challenge-winners",
      title: "IMM Money Heist Challenge - Winners",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `A Money Heist Challenge was conducted in IMM wherein Students using Digital Media shared videos on t`,
      date: "TBD",
      photoCount: 3,
      href: "#",
    },
    {
      id: "hybrid-classes",
      title: "Hybrid Classes",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `IMM opened its doors for Students to start attending classes in the hybrid mode from September 13, 2`,
      date: "September 13, 2021",
      photoCount: 8,
      href: "#",
    },
    {
      id: "teachers-day",
      title: "Teachers Day",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Teachers Day was celebrated with great zest at the IMM campus. Students honored the professors in a`,
      date: "September 5, 2021",
      photoCount: 5,
      href: "#",
    },
    {
      id: "aagaman",
      title: "Aagaman",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `The Aagaman Orientation Day event was filled with fun activities and student interactions to welcome`,
      date: "July 1, 2021",
      photoCount: 5,
      href: "#",
    },
    {
      id: "founders-day",
      title: "Founder’s Day at Campus",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `IMM celebrated its 52nd Founder’s Day and our country’s Independence Day on August 14, 2021 with`,
      date: "August 14, 2021",
      photoCount: 8,
      href: "#",
    },
  ],
  2020: [
    {
      id: "rejuvenate-yoga",
      title: "Rejuvenate: Yoga for a healthy Mind, Body and Soul",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `Rejuvenate: "Yoga for a healthy Mind, Body and Soul": A 5 day capsule course on yoga for destressing`,
      date: "TBD",
      photoCount: 2,
      href: "#",
    },
    {
      id: "stand-up-comedy",
      title: "LIVE Session on Stand-up Comedy Show",
      image: "https://v0.dev/placeholder.svg",
      gallery: [],
      description: `The live Stand Up Comedy Show was really a fun filled session for the students. Mr. Garv Malik touched`,
      date: "TBD",
      photoCount: 1,
      href: "#",
    },
  ],
};
