import img1 from "../../assets/spotlights/cowad.webp";
import img2 from "../../assets/spotlights/pdhm.webp";
import img3 from "../../assets/spotlights/isagdf.webp";
import img4 from "../../assets/spotlights/hvos.webp";
import img5 from "../../assets/spotlights/oolaigc.webp";
import img6 from "../../assets/spotlights/apd.webp";
import img7 from "../../assets/spotlights/hvfos.webp";
import img8 from "../../assets/spotlights/gdgoc.webp";
import img9 from "../../assets/spotlights/tdc.webp";
import img10 from "../../assets/spotlights/thpks.webp";
import img11 from "../../assets/spotlights/ch.webp";
import img12 from "../../assets/spotlights/ph.webp";
import img13 from "../../assets/spotlights/ndd.webp"; // National Doctor's Day
import img14 from "../../assets/spotlights/ee.webp";  // Empowering Educators
import img15 from "../../assets/spotlights/fdp.webp"; // Faculty Development Program
import img16 from "../../assets/spotlights/iyd.webp"; // International Yoga Day
import img17 from "../../assets/spotlights/eaa.webp"; // EID AL-ADHA
import img18 from "../../assets/spotlights/teassk.webp"; // Tools Every Architect Student
import img19 from "../../assets/spotlights/wed.webp"; // World Environment Day
import img20 from "../../assets/spotlights/ch.webp";  // Campus Highlights
import img21 from "../../assets/spotlights/ph.webp";  // Placement Highlights
import img22 from "../../assets/spotlights/cfgacd.webp"; // Center For Guidance and Career Development
import img23 from "../../assets/spotlights/esontd.webp"; // Expert Session on National Technology Day
import img24 from "../../assets/spotlights/md.webp";  // Mother's Day
import img25 from "../../assets/spotlights/cn.webp";  // Coding Ninjas
import img26 from "../../assets/spotlights/iia.webp";  // IGCE & IGCMT Achievers
import img27 from "../../assets/spotlights/esoec.webp"; // Expert Session on Eco-Consciousness
import img28 from "../../assets/spotlights/esoec.webp"; // Session on Eco-Consciousness
import img29 from "../../assets/spotlights/ifgtn.webp"; // IPL Fever Grips the Nation
import img30 from "../../assets/spotlights/cpd.webp";  // Campus Placement Drive




export const eventsData = [
  {
    id: 1,
    date: "October 25, 2024",
    category: "education",
    title: "Celebration of World Anesthesia Day",
    tags: ["Health", "Medical"],
    description: "Celebration of World Anesthesia Day",
    image: img1,
    gallery: [img1],
  },
  {
    id: 2,
    date: "October 10, 2024",
    category: "education",
    title: "Placement Drive - Hoping Minds",
    tags: ["Career", "Placement"],
    description: "Placement Drive - Hoping Minds",
    image: img2,
    gallery: [img2],
  },
  {
    id: 3,
    date: "October 6, 2024",
    category: "education",
    title: "IGC students attended Google Development Fest",
    tags: ["Technology", "Development"],
    description: "IGC students attended Google Development Fest",
    image: img3,
    gallery: [img3],
  },
  {
    id: 4,
    date: "September 26, 2024",
    category: "education",
    title: "Hospital visit - OTT students on 26th September 2024",
    tags: ["Healthcare", "Education"],
    description: "Hospital visit - OTT students on 26th September 2024",
    image: img4,
    gallery: [img4],
  },
  {
    id: 5,
    date: "September 22, 2024",
    category: "education",
    title: "Operational Odyssey Launches at Indo Global Colleges",
    tags: ["Innovation", "Campus"],
    description: "Operational Odyssey Launches at Indo Global Colleges",
    image: img5,
    gallery: [img5],
  },
  {
    id: 6,
    date: "September 17, 2024",
    category: "education",
    title: "AspireFox Placement Drive - 17th Sep 2024",
    tags: ["Career", "Placement"],
    description: "AspireFox Placement Drive - 17th Sep 2024",
    image: img6,
    gallery: [img6],
  },
  {
    id: 7,
    date: "September 23, 2024",
    category: "education",
    title: "Hospital Visit for OTT students",
    tags: ["Healthcare", "Education"],
    description: "Hospital Visit for OTT students",
    image: img7,
    gallery: [img7],
  },
  {
    id: 8,
    date: "September 18, 2024",
    category: "education",
    title: "Google Developer Groups on Campus",
    tags: ["Technology", "Development"],
    description: "Google Developer Groups on Campus",
    image: img8,
    gallery: [img8],
  },
  {
    id: 9,
    date: "May 5, 2024",
    category: "education",
    title: "Teacher's Day Celebration 2024",
    tags: ["Celebration", "Education"],
    description: "Celebrating Teacher's Day with special events and honors",
    image: img9,
    gallery: [img9],
  },
  {
    id: 10,
    date: "September 25, 2024",
    category: "education",
    title: "Talent Hunt Program Knack Seek - 2024",
    tags: ["Talent", "Recruitment"],
    description: "A program to identify and nurture talented students",
    image: img10,
    gallery: [img10],
  },
  {
    id: 11,
    date: "July 15, 2024",
    category: "education",
    title: "Youth Skills Day",
    tags: ["Youth", "Skills"],
    description: "Youth Skills Day event focused on enhancing student skills",
    image: img11,
    gallery: [img11],
  },
  {
    id: 12,
    date: "July 2, 2024",
    category: "education",
    title: "T20 World Cup Trophy",
    tags: ["Sports", "Celebration"],
    description: "Celebrating the T20 World Cup with a trophy ceremony",
    image: img12,
    gallery: [img12],
  },
  {
    id: 13,
    date: "July 1, 2024",
    category: "education",
    title: "National Doctor's Day",
    tags: ["Healthcare", "Appreciation"],
    description: "Honoring doctors on National Doctor's Day",
    image: img13,
    gallery: [img13],
  },
  {
    id: 14,
    date: "July 1, 2024",
    category: "education",
    title: "Empowering Educators",
    tags: ["Education", "Professional Development"],
    description: "Workshops and seminars to empower educators",
    image: img14,
    gallery: [img14],
  },
  {
    id: 15,
    date: "June 23, 2024",
    category: "education",
    title: "Faculty Development Program",
    tags: ["Education", "Training"],
    description:
      "Enhancing faculty skills through targeted development programs",
    image: img15,
    gallery: [img15],
  },
  {
    id: 16,
    date: "June 21, 2024",
    category: "education",
    title: "International Yoga Day",
    tags: ["Health", "Wellness"],
    description: "Celebrating International Yoga Day with various activities",
    image: img16,
    gallery: [img16],
  },
  {
    id: 17,
    date: "June 17, 2024",
    category: "education",
    title: "EID AL-ADHA",
    tags: ["Cultural", "Religious"],
    description: "Celebrating EID AL-ADHA with community events",
    image: img17,
    gallery: [img17],
  },
  {
    id: 18,
    date: "June 6, 2024",
    category: "education",
    title: "Tools Every Architect Student Should Know",
    tags: ["Architecture", "Technology"],
    description: "Introducing essential tools for architecture students",
    image: img18,
    gallery: [img18],
  },
  {
    id: 19,
    date: "June 5, 2024",
    category: "education",
    title: "World Environment Day",
    tags: ["Environment", "Sustainability"],
    description: "Activities and awareness programs for World Environment Day",
    image: img19,
    gallery: [img19],
  },
  {
    id: 20,
    date: "May 31, 2024",
    category: "education",
    title: "Campus Highlights",
    tags: ["Achievement", "Campus Life"],
    description:
      "Showcasing the latest highlights and achievements of the campus",
    image: img20,
    gallery: [img20],
  },
  {
    id: 21,
    date: "May 29, 2024",
    category: "education",
    title: "Placement Highlights",
    tags: ["Career", "Success"],
    description:
      "Highlights from recent placement drives and student successes",
    image: img21,
    gallery: [img21],
  },
  {
    id: 22,
    date: "May 27, 2024",
    category: "education",
    title: "Centre for Guidance and Career Development",
    tags: ["Career", "Guidance"],
    description: "Launch of the new Centre for Guidance and Career Development",
    image: img22,
    gallery: [img22],
  },
  {
    id: 23,
    date: "May 13, 2024",
    category: "education",
    title: "Expert Session on National Technology Day",
    tags: ["Technology", "Innovation"],
    description:
      "An expert-led session discussing advancements on National Technology Day",
    image: img23,
    gallery: [img23],
  },
  {
    id: 24,
    date: "May 12, 2024",
    category: "education",
    title: "Mother's Day",
    tags: ["Celebration", "Family"],
    description: "Celebrating Mother's Day with special events and honors",
    image: img24,
    gallery: [img24],
  },
  {
    id: 25,
    date: "May 3, 2024",
    category: "education",
    title: "Coding Ninjas",
    tags: ["Technology", "Coding"],
    description:
      "Workshop on advanced coding techniques hosted by Coding Ninjas",
    image: img25,
    gallery: [img25],
  },
  {
    id: 26,
    date: "May 1, 2024",
    category: "education",
    title: "IGCE & IGCMT Achievers",
    tags: ["Achievement", "Recognition"],
    description: "Recognizing the achievements of IGCE & IGCMT students",
    image: img26,
    gallery: [img26],
  },
  {
    id: 27,
    date: "April 25, 2024",
    category: "education",
    title: "Expert Session on Eco-Consciousness",
    tags: ["Environment", "Sustainability"],
    description: "An expert-led session on promoting eco-consciousness",
    image: img27,
    gallery: [img27],
  },
  {
    id: 28,
    date: "April 23, 2024",
    category: "education",
    title: "Session on Eco-Consciousness",
    tags: ["Environment", "Sustainability"],
    description: "Interactive session focusing on eco-conscious practices",
    image: img28,
    gallery: [img28],
  },
  {
    id: 29,
    date: "April 23, 2024",
    category: "education",
    title: "IPL Fever Grips the Nation",
    tags: ["Sports", "Entertainment"],
    description: "Celebrating the excitement of IPL with various events",
    image: img29,
    gallery: [img29],
  },
  {
    id: 30,
    date: "April 20, 2024",
    category: "education",
    title: "Campus Placement Drive",
    tags: ["Career", "Placement"],
    description: "Conducting a major placement drive for graduating students",
    image: img30,
    gallery: [img30],
  },
  // {
  //   id: 31,
  //   date: "April 19, 2024",
  //   category: "education",
  //   title: "Discover Excellence at Indo Global Colleges",
  //   tags: ["Achievement", "Education"],
  //   description: "Showcasing excellence in education at Indo Global Colleges",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 32,
  //   date: "April 19, 2024",
  //   category: "education",
  //   title: "Prestigious IGC MBA Program!",
  //   tags: ["Education", "MBA"],
  //   description:
  //     "Launching the prestigious IGC MBA Program for aspiring leaders",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 33,
  //   date: "April 12, 2024",
  //   category: "education",
  //   title: "Blood Donation Camp",
  //   tags: ["Community", "Healthcare"],
  //   description: "Organizing a blood donation camp to support the community",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 34,
  //   date: "April 9, 2024",
  //   category: "education",
  //   title: "CODE CRAZE - Winners",
  //   tags: ["Technology", "Competition"],
  //   description: "Announcing the winners of the CODE CRAZE competition",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 35,
  //   date: "April 5, 2024",
  //   category: "education",
  //   title: "Industrial Visit to RAC Plant at VERKA Chandigarh",
  //   tags: ["Industrial", "Learning"],
  //   description:
  //     "Educational industrial visit to the RAC Plant at VERKA Chandigarh",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 36,
  //   date: "April 5, 2024",
  //   category: "education",
  //   title: "International Economy and Promote Maritime Trade",
  //   tags: ["Economy", "Global Trade"],
  //   description:
  //     "Seminar on international economy and maritime trade promotion",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 37,
  //   date: "April 1, 2024",
  //   category: "education",
  //   title: "IGC Coding Club",
  //   tags: ["Technology", "Coding"],
  //   description: "Launching the IGC Coding Club for aspiring programmers",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 38,
  //   date: "March 27, 2024",
  //   category: "education",
  //   title: "Hospital/Lab Visit",
  //   tags: ["Healthcare", "Practical Learning"],
  //   description:
  //     "Educational visit to local hospitals and labs for practical exposure",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 39,
  //   date: "March 20, 2024",
  //   category: "education",
  //   title: "The Euphoric Managers 2024",
  //   tags: ["Management", "Leadership"],
  //   description: "Conference for aspiring managers to enhance their skills",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 40,
  //   date: "March 20, 2024",
  //   category: "education",
  //   title: "Techno Vista",
  //   tags: ["Technology", "Innovation"],
  //   description:
  //     "Exhibition showcasing the latest in technology and innovation",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 41,
  //   date: "March 18, 2024",
  //   category: "education",
  //   title: "The Euphoric Managers",
  //   tags: ["Management", "Leadership"],
  //   description: "Follow-up session for The Euphoric Managers program",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 42,
  //   date: "March 16, 2024",
  //   category: "education",
  //   title: "17 Convocation",
  //   tags: ["Achievement", "Graduation"],
  //   description: "Ceremony celebrating the 17th convocation of graduates",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 43,
  //   date: "March 13, 2024",
  //   category: "education",
  //   title: "The Convocation Ceremony",
  //   tags: ["Graduation", "Achievement"],
  //   description: "Formal convocation ceremony for graduating students",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 44,
  //   date: "March 11, 2024",
  //   category: "education",
  //   title: "Best Out of Waste",
  //   tags: ["Creativity", "Sustainability"],
  //   description: "Creative workshop on recycling and repurposing materials",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 45,
  //   date: "March 11, 2024",
  //   category: "education",
  //   title: "IGC Coding Club",
  //   tags: ["Technology", "Coding"],
  //   description: "Monthly meetup for members of the IGC Coding Club",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 46,
  //   date: "March 1, 2024",
  //   category: "education",
  //   title: "The National Science Day",
  //   tags: ["Science", "Innovation"],
  //   description:
  //     "Celebrating National Science Day with various scientific activities",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 47,
  //   date: "March 1, 2024",
  //   category: "education",
  //   title: "ACE Group Discussion",
  //   tags: ["Communication", "Learning"],
  //   description: "Group discussions organized by the ACE committee",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 48,
  //   date: "February 28, 2024",
  //   category: "education",
  //   title: "National Science Day",
  //   tags: ["Science", "Education"],
  //   description: "Annual celebrations and events for National Science Day",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 49,
  //   date: "February 27, 2024",
  //   category: "education",
  //   title: "National Science Day",
  //   tags: ["Science", "Learning"],
  //   description: "Another session celebrating National Science Day",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 50,
  //   date: "February 23, 2024",
  //   category: "education",
  //   title: "Annual Sports Meets - 2024",
  //   tags: ["Sports", "Competition"],
  //   description: "Annual sports meets highlighting various athletic events",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 51,
  //   date: "February 22, 2024",
  //   category: "education",
  //   title: "Investor Awareness Program",
  //   tags: ["Finance", "Education"],
  //   description:
  //     "Program designed to enhance investor awareness among students",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 52,
  //   date: "February 21, 2024",
  //   category: "education",
  //   title: "Future Trends in Red Hat Linux",
  //   tags: ["Technology", "Linux"],
  //   description: "Seminar on future trends and developments in Red Hat Linux",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 53,
  //   date: "February 21, 2024",
  //   category: "education",
  //   title: "Industrial Visits",
  //   tags: ["Learning", "Industry"],
  //   description: "Organizing industrial visits to enhance practical knowledge",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 54,
  //   date: "March 20, 2023",
  //   category: "education",
  //   title: "Career Opportunities",
  //   tags: ["Career", "Guidance"],
  //   description: "Exploring various career opportunities available to students",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 55,
  //   date: "February 16, 2024",
  //   category: "education",
  //   title: "Expert Session on Inspiring Mind, Shaping Careers",
  //   tags: ["Career", "Inspiration"],
  //   description:
  //     "Expert-led session on inspiring minds and shaping future careers",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 56,
  //   date: "February 16, 2024",
  //   category: "education",
  //   title: "Industrial Visit",
  //   tags: ["Learning", "Industry"],
  //   description:
  //     "Detailed industrial visit to understand real-world applications",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 57,
  //   date: "February 13, 2024",
  //   category: "education",
  //   title: "Glimpses of Expert Session on Blockchain Technologies",
  //   tags: ["Technology", "Innovation"],
  //   description:
  //     "Highlights from the expert session on blockchain technologies",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 58,
  //   date: "February 9, 2024",
  //   category: "education",
  //   title: "Inspiring Minds Shaping Careers",
  //   tags: ["Career", "Inspiration"],
  //   description: "Session focused on inspiring students to shape their careers",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 59,
  //   date: "February 9, 2024",
  //   category: "education",
  //   title: "Blockchain Technologies",
  //   tags: ["Technology", "Innovation"],
  //   description: "Workshop on the latest trends in blockchain technologies",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 60,
  //   date: "February 4, 2024",
  //   category: "education",
  //   title: "Best Infrastructure School of the Year",
  //   tags: ["Achievement", "Infrastructure"],
  //   description: "Awarding the best infrastructure in educational institutions",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 61,
  //   date: "February 2, 2024",
  //   category: "education",
  //   title: "Hamari Baat Aapke Saath",
  //   tags: ["Communication", "Community"],
  //   description: "Interactive session series: Hamari Baat Aapke Saath",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 62,
  //   date: "February 1, 2024",
  //   category: "education",
  //   title: "Keynote Speaker",
  //   tags: ["Inspiration", "Learning"],
  //   description: "Keynote speech by industry leaders on current trends",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 63,
  //   date: "January 31, 2024",
  //   category: "education",
  //   title: "Hamari Baat Aapke Saath Series 2",
  //   tags: ["Communication", "Community"],
  //   description:
  //     "Continuation of the Hamari Baat Aapke Saath interactive sessions",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 64,
  //   date: "January 26, 2024",
  //   category: "education",
  //   title: "Namo Navmatada Sammelan",
  //   tags: ["Cultural", "Community"],
  //   description: "Cultural fest celebrating Navmatada traditions and values",
  //   image: "",
  //   gallery: [],
  // },
  // {
  //   id: 65,
  //   date: "January 23, 2024",
  //   category: "education",
  //   title: "Indian Society of Radiographers and Technologists",
  //   tags: ["Healthcare", "Professional"],
  //   description:
  //     "Collaboration event with the Indian Society of Radiographers and Technologists",
  //   image: "",
  //   gallery: [],
  // },
];
